const textMap = {
  text_1: 'Welcome to MebelHouse - Your Dream Furniture Destination',
  text_2: 'Elevate Your Living Spaces with Our Elegant Furniture Collections',
  text_3: 'Discover Our Range',
  text_4: 'Browse Our Exquisite Furniture Portfolio',
  text_5: 'Chosen by Design Enthusiasts Worldwide',
  text_6: 'Explore Our Diverse Furniture Services',
  text_7: 'Delve into the Versatility of Our Furniture Catalog',
  text_8: 'Enhance Your Home with Our Stylish and Comfortable Furniture',
  text_9: 'Crafting Comfort: Our Premium Sofa Selection',
  text_10: 'Designing Dreams: Our Unique Approach to Furniture',
  text_11: 'MebelHouse: A Synonym for Quality and Elegance',
  text_12: 'Experience Luxury and Durability with Our Furniture',
  text_13: 'From Classic to Contemporary: Furniture for Every Style',
  text_14: 'Innovative Designs for Modern Living',
  text_15: 'Transforming Spaces with Timeless Furniture Pieces',
  text_16: 'Artisan Craftsmanship in Every Furniture Piece',
  text_17: 'Schedule a Consultation with Our Furniture Experts',
  text_18: 'View Our Latest Furniture Collection Online',
  text_19: 'MebelHouse: Crafting Your Furniture Dreams',
  text_20: 'Discover the Story Behind Our Exquisite Furniture Making',
  text_21: 'Crafting Spaces: The Art of Fine Furniture',
  text_22: 'The Elegance of Modern Living with MebelHouse',
  text_23: 'Quality Furniture for a Timeless Home Aesthetic',
  text_24: 'Bringing Comfort and Style to Your Home',
  text_25: 'MebelHouse: Where Design Meets Durability',
  text_26: 'Sophisticated Furniture for Discerning Tastes',
  text_27: 'Innovative Furniture Solutions for Modern Homes',
  text_28: 'MebelHouse: Weaving Elegance into Every Thread',
  text_29: 'Furnishing Dreams with Unmatched Craftsmanship',
  text_30: 'The Essence of Comfort in Home Furnishings',
  text_31: 'Sustainable and Chic - Furniture with a Conscience',
  text_32: 'The Art of Furniture: Design, Craft, Elegance',
  text_33: 'Furniture That Tells a Story',
  text_34: "Inspired Living with MebelHouse's Signature Collections",
  text_35: 'Unveiling the Beauty of Bespoke Furniture',
  text_36: 'Designing Spaces with Personality and Comfort',
  text_37: 'Furniture as an Expression of Art',
  text_38: 'MebelHouse: Crafting Your Ideal Living Space',
  text_39: 'Elevate Your Space with Our Contemporary Designs',
  text_40: 'Embrace Luxury in Every Detail with MebelHouse',
  text_41: 'Revitalize Your Home with Our Exclusive Furniture Pieces',
  text_42: 'MebelHouse: Redefining Comfort and Style',
  text_43: 'Experience Luxury in Every Stitch and Carving',
  text_44: 'Your Destination for Premium Home Furnishings',
  text_45: 'The Art of Fine Living Begins with MebelHouse',
  text_46: 'Elevating Interiors with Elegant Furniture Designs',
  text_47: 'MebelHouse - Where Dreams Merge with Reality',
  text_48: 'Find Your Perfect Match in Our Furniture Collections',
  text_49: 'Crafting Excellence in Every Furniture Design',
  text_50: 'Explore the Fusion of Innovation and Tradition at MebelHouse',
  text_51: 'A Symphony of Style and Function in Furniture',
  text_52: 'Creating Harmonious Spaces with MebelHouse',
  text_53: 'Where Quality Meets Elegance in Furniture Design',
  text_54: 'Transform Your Home into a Haven of Style',
  text_55: 'MebelHouse: Your Partner in Home Beautification',
  text_56: 'Crafting Spaces to Inspire and Comfort',
  text_57: 'Bespoke Furniture to Reflect Your Personal Style',
  text_58: 'Indulge in the Luxury of Handcrafted Furniture',
  text_59: 'MebelHouse: Synonymous with Sophistication and Durability',
  text_60: 'Experience the MebelHouse Difference in Every Room',
  text_61: 'MebelHouse: A World of Stylish and Functional Furniture',
  text_62: 'Uncover the Beauty of Craftsmanship with Our Furniture',
  text_63: 'Design-Forward Furniture for the Modern Home',
  text_64: "Curating Spaces with MebelHouse's Unique Pieces",
  text_65: 'Experience Elegance in Every Furniture Element',
  text_66: 'MebelHouse: Where Design Meets Practicality',
  text_67: 'Step into the World of Luxurious Furnishings',
  text_68: 'Celebrate Style with Our Contemporary Furniture Range',
  text_69: 'The MebelHouse Promise: Quality in Every Detail',
  text_70: 'Transformative Designs for Your Personal Oasis',
  text_71: "MebelHouse: Crafting Spaces You'll Love",
  text_72: 'Bringing Your Vision to Life with Elegant Furnishings',
  text_73: 'A New Era of Home Decor with MebelHouse',
  text_74: 'Furniture That Makes a Statement',
  text_75: 'Define Your Space with Our Unique Furniture',
  text_76: 'MebelHouse: The Art of Sophisticated Living',
  text_77: 'Exquisite Furniture for a Refined Lifestyle',
  text_78: 'Innovative Furniture Designs for Every Taste',
  text_79: 'MebelHouse: Inspiring Designs, Timeless Comfort',
  text_80: 'Your Journey to Luxury Living Starts Here',
  text_81: "Revamp Your Home with MebelHouse's Fine Furnishings",
  text_82: 'MebelHouse: Where Comfort Meets High-End Design',
  text_83: 'Bridging Elegance and Practicality in Furniture',
  text_84: 'Furniture Masterpieces for the Discerning Eye',
  text_85: 'MebelHouse: A Tradition of Excellence in Furniture',
  text_86: 'Discover the Charm of Hand-Crafted Furniture',
  text_87: 'MebelHouse - Crafting Your Ideal Home',
  text_88: 'The Ultimate Furniture Experience Awaits You',
  text_89: 'Innovating Home Decor with MebelHouse Creations',
  text_90: 'Where Every Furniture Tells a Story',
  text_91: 'Elevate Your Lifestyle with MebelHouse Furnishings',
  text_92: 'Inspiration in Every Furniture Design',
  text_93: 'MebelHouse: A Reflection of Your Taste',
  text_94: 'Crafting Future Heirlooms with Unique Designs',
  text_95: 'Unveiling the Future of Furniture at MebelHouse',
  text_96: 'Your Gateway to an Exquisite Home',
  text_97: 'MebelHouse: Redefining Home Aesthetics',
  text_98: 'A New Perspective on Classic Furnishing',
  text_99: 'MebelHouse: Where Dreams of Comfort Become Reality',
  text_100: 'Join the MebelHouse Family of Satisfied Customers',
  text_101: 'MebelHouse: Synthesizing Comfort and Innovation',
  text_102: 'Step into Luxury with Our Premium Furniture Line',
  text_103: 'Crafting Timeless Elegance for Every Home',
  text_104: 'MebelHouse: Where Every Piece is a Masterpiece',
  text_105: 'Reimagine Your Living Space with Our Designs',
  text_106: 'A Fusion of Functionality and Art in Furniture',
  text_107: 'Redefine Your Home with MebelHouse',
  text_108: 'Transforming Interiors with Creative Flair',
  text_109: 'MebelHouse: Crafting Future Classics',
  text_110: 'Experience the Intersection of Comfort and Style',
  text_111: 'From Sketch to Reality: Our Furniture Journey',
  text_112: 'MebelHouse: Elevating Spaces, Enriching Lives',
  text_113: 'Discover the Ultimate in Home Furnishing',
  text_114: 'MebelHouse: A Legacy of Design Excellence',
  text_115: 'Bringing Artistic Vision to Furniture Design',
  text_116: 'MebelHouse: Crafting the Heart of Your Home',
  text_117: 'Every Detail Matters in Our Furniture Creations',
  text_118: 'Elegance and Comfort in Every MebelHouse Piece',
  text_119: 'MebelHouse: A Symphony of Style and Substance',
  text_120: "Transform Your Space with MebelHouse's Elegance",
  text_121: 'MebelHouse: Where Design Dreams Come to Life',
};

module.exports = textMap;
